title: 平成.rb

description: |
  平成.rbは平成生まれのRubyエンジニアを対象とした勉強会です。 LT会とモブプロ会を交互に行っております。

lang: ja
timezone: Asia/Tokyo

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- vendor/
- .git/
- .ruby-version

theme: jekyll-theme-cayman

github_username: heiseirb

twitter:
  card: summary_large_image
  username: heiseirb

# google_analytics: [Your Google Analytics tracking ID]

livereload: true